knp_snappy:
    pdf:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"'
        options:    
            - { name: 'viewport-size', value: '1280x1024' }
            - { name: 'page-size', value: 'A4' }
    image:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"'
        options:    []
